name: Build Sunshine (Windows)

on:
  workflow_dispatch: # 支持手动触发

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      # 检出代码，不处理子模块
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: false

      # 安装 MSYS2
      - name: Install MSYS2
        run: |
          choco install msys2 -y
          $env:PATH = 'C:\tools\msys64\usr\bin;C:\tools\msys64\mingw64\bin;' + $env:PATH

      # 更新 MSYS2 并安装依赖项
      - name: Update MSYS2 and install dependencies
        run: |
          bash -lc "pacman -Syu --noconfirm"
          bash -lc "pacman -S --noconfirm mingw-w64-ucrt-x86_64-{boost,cmake,cppwinrt,curl-winssl,graphviz,MinHook,miniupnpc,nlohmann-json,nodejs,nsis,onevpl,openssl,opus,toolchain}"

      # 构建项目
      - name: Build project
        run: |
          mkdir build
          cmake -B build -G Ninja -S .
          ninja -C build

      # 打包项目
      - name: Package project (NSIS and ZIP)
        run: |
          cpack -G NSIS --config ./build/CPackConfig.cmake
          cpack -G ZIP --config ./build/CPackConfig.cmake
